# Generated by Django 2.1.8 on 2019-05-07 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jplayer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jplayerintermediate',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='jplayer_jplayerintermediate', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='song',
            name='mp3_file',
            field=models.FileField(upload_to='songs/mp3/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='ogg_file',
            field=models.FileField(blank=True, null=True, upload_to='songs/ogg/'),
        ),
    ]
